# this config file is used for running the template default tests

model:
  _target_: src.modules.models.squeezenet.SqueezeNet1_1Module
  finetune: true
  weights: null
  num_classes: ${num_classes}
  trainable_feature_layers: null

loss:
  _target_: torch.nn.CrossEntropyLoss

metrics:
  main:
    _target_: "torchmetrics.Accuracy"
    task: "multiclass"
    num_classes: ${num_classes}
    top_k: 1
  valid_best:
    _target_: "torchmetrics.MaxMetric"
output_activation: null
