train:
  order: ["resize", "normalize"]
  resize:
    _target_: albumentations.Resize
    height: 224
    width: 224
    p: 1.0
  normalize:
    _target_: albumentations.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    p: 1.0

valid_test_predict:
  order: ["resize", "normalize"]
  resize:
    _target_: albumentations.Resize
    height: 224
    width: 224
    p: 1.0
  normalize:
    _target_: albumentations.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    p: 1.0
